### PR TITLE
Rajesh Vig - Updated sv_sec_data.sql to fix broken page urls and edit…

### PR DESCRIPTION
**Pull request by rajeshvig**
- Made changes for apex 19.1, certain builder app pages references were obsolete, replaced page ids in accordance with apex 19.1.

- updates pages broken due query returning column name as result on 19.1 by using aliases on query, page column kept the same as Result. 

- Changed impacted pages to use dynamic processing for highlighting results instead of saved IR report

### CODE REVIEW

**Comment by rajeshvig** [comment]
hi @sspendol  ,
 did you get a chance to review the change?

**Comment by TonyCMiller** [comment]
Will you be making changes to support APEX 19.2?

Thank you,

Tony Miller
White Rock, NM

**Comment by rajeshvig** [comment]
No committed date yet but will try on that as well

**Comment by sspendol** [comment]
I have not had a chance and likely won't for a while.  I would recommend branching this if you want to make updates.

**Comment by rajeshvig** [comment]
@sspendol looks like i can't add a branch to base repo. how about you spawn 19.1 branch on the repo so we can have my fork changes available on that branch instead? if its still not ok then will continue work on my fork instead

**Comment by rajeshvig** [comment]
@TonyCMiller tested changes done for 19.1 are good for 19.2 as well. You can try out the 19.2 bundle from https://github.com/rajeshvig/apex-sert/tree/19.2

**Comment by sspendol** [comment]
I prefer to keep it on your fork for now if that's OK.  Thanks.

**Comment by rajeshvig** [comment]
Sure

**Comment by TonyCMiller** [comment]
Can you send a link to download the latest build so I could try use it?

Thank you,

Tony Miller
White Rock, NM

**Comment by rajeshvig** [comment]
you can pick it from https://github.com/rajeshvig/apex-sert/tree/19.2/releases

**Pull request closed without merging**
